### ISSUE TITLE
Create Intent transformations

### ISSUE THREAD

**Issue by Gauhar** [Botmock/sdk#567]
Create intent transformations from Botmock's intents to what CX likes

**Comment by rahulchauhan049** [comment]
The task is to use resources from botmock and create an object name intent. The structure of this intent was going to be too specific because the dialogflow cx connector expects the intent object to be in this structure.

Object `intent` is going to be an array of objects. Each object contains name, training phrases, entities used(parameters), and description. This intent uses the entity `foodMenu` for example

The CLI replaces the id of each entity with an actual id of that entity while running.

```jsx
[
	{
      "displayName": "foodOrder",
      "trainingPhrases": [
          {
              "id": "58407164-0c54-4b1f-a435-ae0ceb7dacc8",
              "parts": [
                  {"text": "I want a"},
                  {"text": "pizza", "parameterId": "foodMenu"}
              ],
              "repeatCount": 1
          }
      ],
      "parameters": [
        {
          "id": "foodMenu",
          "entityType": "",
          "isList": true,
          "redact": false
        }
      ],
      "priority": 500000,
      "isFallback": false,
      "description": "test intent description"
  }
]
```

**Comment by rahulchauhan049** [comment]
In dialogflowCX exporter, there's going to be a method that'll covert the botmock intent into this structure.

The process may be divided into following

- [ ] Create method for intent transformation
- [ ] Take Each intent and create object which contains the above keys like displaName. Most of the things can be directly mapped.
- [ ] Create trainingPhrases. 
    - [ ] Find variable and create parts accordingly 
- [ ] Find entities used in training phrase and add those to parameters
