### ISSUE TITLE
Create resource JSON which is Dialogflow CX friendly

### ISSUE THREAD

**Issue by Gauhar** [Botmock/sdk#572]
@rahulchauhan049  - The stage is yours :) :D

**Comment by Gauhar** [comment]
Added 8 hours and we can change it if it takes longer or shorter.

**Comment by Gauhar** [comment]
![Screenshot 1 -01](https://user-images.githubusercontent.com/3247111/113004018-44e9b200-9141-11eb-995d-130bb846ada1.png)

**Comment by rahulchauhan049** [comment]
This JSON file is what is going to be exported by our cx dialogflow exporter.

This object is going to contain 5 keys, naming `flows`, `pages`, 'intents`, 'entities`, and `agent`.

Our CX Export in CLI will use this JSON to create the whole project in CX using different APIs provided by dialogflow.

The flow of calling different APIs has to be in a very specific order. For example is we can't create intents, without creating entities first because we need id's on entities.
